### ISSUE TITLE
Неожиданное поведение сервера при отправке ему чего попало вместо идентификатора State'а

### ISSUE THREAD

**Issue by emnigma** [gsvgit/VSharp#10]
При отправке на сервер сериализированного State вместо его айди он продолжает работать

Вот ветка с кодом:
https://github.com/emnigma/VSharp/tree/unexpected_server_answer

Вот тут присылается State вместо его Id:
https://github.com/emnigma/VSharp/blob/3af2bca5e0121fd37760b7ff4fdd5bb2dd0f6c75/VSharp.ML.AIAgent/old_agent_launch.py#L55

На сервер приходит вот такой json в итоге:

```
{"MessageType": "step", "MessageBody": "{\\"StateId\\": {\\"Id\\": 0, \\"Position\\": 1, \\"PredictedUsefulness\\": 0, \\"PathConditionSize\\": 1, \\"VisitedAgainVertices\\": 0, \\"VisitedNotCoveredVerticesInZone\\": 0, \\"VisitedNotCoveredVerticesOutOfZone\\": 0, \\"History\\": [0], \\"Children\\": []}, \\"PredictedStateUsefulness\\": 42.0}"}
```

вот он же не экранированный:

```
{
    "MessageType": "step",
    "MessageBody": "{StateId: {Id: 0, Position: 1, PredictedUsefulness: 0, PathConditionSize: 1, VisitedAgainVertices: 0, VisitedNotCoveredVerticesInZone: 0, VisitedNotCoveredVerticesOutOfZone: 0, History: [0], Children: []}, PredictedStateUsefulness: 42.0}"
}
```

логи:
[unexpected.log](https://github.com/gsvgit/VSharp/files/10540679/unexpected.log)

**Comment by gsvgit** [comment]
@emnigma кажется, проблема в том, что в используемом мной json-десериализаторе впринципе непредусмотрена валидация. Если вход некорректен, он просто инстанциирует объект нужного типа и всё. А его дальше уже сложно отличить от "валидного". Подумаю, можно ли с этим что-то сделать, не городя огород.

**Comment by emnigma** [comment]
> @emnigma кажется, проблема в том, что в используемом мной json-десериализаторе впринципе непредусмотрена валидация. Если вход некорректен, он просто инстанциирует объект нужного типа и всё. А его дальше уже сложно отличить от "валидного". Подумаю, можно ли с этим что-то сделать, не городя огород.

я думаю, что это не первоочередная задача. если тестировать одно получаемое значение, то почему не тестировать все. раз мы агенту "доверяем", то можно ожидать, что он не будет кидать в сервер что попало

**Comment by gsvgit** [comment]
Вроде, пофиксил "мимоходом". @emnigma, можете на всякий случай перепроверить?
