### ISSUE TITLE
Добавить логгирование обучения

### ISSUE THREAD

**Issue by emnigma** [gsvgit/VSharp#23]
бахнуть модуль логгирования: либу logging, разные уровни verbosity, круто было бы рисовать табличку с результатами каждой нейронки

**Comment by gsvgit** [comment]
Скорее, всех нейронок: просто сводная таблица по поколению. Все нейронки поколения и все карты. Ну и дяльше для каждой нейронки и карты --- результаты нейронки на карте. Может быть прогресс-бар для каждой нейронки в процессе её игры или что-то такое. Чтобы видеть, не звисла ли конкретна игра случайно.

**Comment by emnigma** [comment]
https://github.com/gsvgit/VSharp/pull/26
