### ISSUE TITLE
Корректно ресетить состояние сервера при окончании игры

### ISSUE THREAD

**Issue by gsvgit** [gsvgit/VSharp#7]
Сервер должен уметь корректно играть подряд несколько игр. Сейчас есть проблемы.
1. [Раз](https://github.com/gsvgit/VSharp/pull/5#issuecomment-1399033555)
2. [Два](https://github.com/gsvgit/VSharp/pull/5#issuecomment-1399034973)

**Comment by emnigma** [comment]
закрываем?

**Comment by gsvgit** [comment]
@emnigma Если проверили и работает, то да, закрываем.
